#!/usr/bin/env bash
# =============================================================================
# modules/40-optimizations.sh -- System performance and SSD optimizations
# swappiness, I/O scheduler, TRIM, journald, dnf-makecache timer
# =============================================================================

MODULE_NAME="40-optimizations"

module_40_optimizations() {
  log_section "Module: Performance and Optimizations"

  _configure_sysctl
  _configure_io_scheduler
  _configure_trim
  _configure_journald
  _configure_dnf_makecache_timer
  _configure_boot_behavior

  log_success "Module $MODULE_NAME completed."
}

_configure_boot_behavior() {
    step "Configuring boot and session behavior"

    sudo systemctl disable NetworkManager-wait-online.service >/dev/null 2>&1 || true
    sudo rm -f /etc/xdg/autostart/org.gnome.Software.desktop >/dev/null 2>&1 || true

    ok "Boot behavior configured."
}

# -----------------------------------------------------------------------------
_configure_sysctl() {
  step "Configuring kernel parameters (sysctl)"

  local conf_file="/etc/sysctl.d/99-finitra.conf"

  # Idempotent: always rewrite with current config values
  run_as_root tee "$conf_file" > /dev/null << SYSCTLEOF
# Generated by finitra -- $(date)
# --- Memory and Swap ---
# Reduce swap usage; ZRAM compresses in RAM before hitting disk
vm.swappiness = ${VM_SWAPPINESS:-10}
# Prefer keeping inode/dentry cache (benefits SSD + dev workloads)
vm.vfs_cache_pressure = 50

# --- Network (useful for container workloads) ---
net.core.somaxconn = 4096
net.ipv4.tcp_fastopen = 3
SYSCTLEOF

  run_as_root sysctl --system &>/dev/null || run_as_root sysctl -p "$conf_file"
  ok "sysctl configured (swappiness=${VM_SWAPPINESS:-10})"
}

# -----------------------------------------------------------------------------
_configure_io_scheduler() {
  step "Configuring I/O scheduler for SSD (mq-deadline / none)"

  local udev_rule="/etc/udev/rules.d/60-ioschedulers.conf"

  if [[ ! -f "$udev_rule" ]]; then
    run_as_root tee "$udev_rule" > /dev/null << 'UDEVEOF'
# I/O scheduler optimized for SSD (NVMe and SATA SSD)
# Generated by finitra

# NVMe -- no scheduler (hardware manages the queue)
ACTION=="add|change", KERNEL=="nvme[0-9]*", ATTR{queue/scheduler}="none"

# SATA SSD -- mq-deadline (low latency)
ACTION=="add|change", KERNEL=="sd[a-z]", ATTR{queue/rotational}=="0", ATTR{queue/scheduler}="mq-deadline"

# HDD -- bfq (fair queuing, if present)
ACTION=="add|change", KERNEL=="sd[a-z]", ATTR{queue/rotational}=="1", ATTR{queue/scheduler}="bfq"
UDEVEOF
    run_as_root udevadm control --reload-rules
    run_as_root udevadm trigger --type=devices --action=change 2>/dev/null || true
    ok "I/O scheduler udev rules applied"
  else
    skip "I/O scheduler rules already present"
  fi
}

# -----------------------------------------------------------------------------
_configure_trim() {
  if [[ "${ENABLE_SSD_TRIM:-true}" != "true" ]]; then
    skip "SSD TRIM disabled in config"
    return
  fi

  step "Enabling weekly TRIM (fstrim.timer)"

  if ! is_service_enabled "fstrim.timer"; then
    run_as_root systemctl enable --now fstrim.timer
    ok "fstrim.timer enabled"
  else
    skip "fstrim.timer already enabled"
  fi

  # Run TRIM immediately once
  run_as_root fstrim -av 2>/dev/null || true
}

# -----------------------------------------------------------------------------
_configure_journald() {
  step "Limiting journald disk usage"

  local max_size="${JOURNALD_MAX_SIZE:-100M}"
  local max_files="${JOURNALD_MAX_FILES:-5}"
  local conf_dir="/etc/systemd/journald.conf.d"
  local conf_file="${conf_dir}/99-finitra.conf"

  run_as_root mkdir -p "$conf_dir"

  local desired
  desired=$(cat << JOURNALEOF
# Generated by finitra
[Journal]
SystemMaxUse=${max_size}
SystemMaxFiles=${max_files}
Compress=yes
JOURNALEOF
)

  if [[ ! -f "$conf_file" ]] || ! diff <(echo "$desired") "$conf_file" &>/dev/null; then
    echo "$desired" | run_as_root tee "$conf_file" > /dev/null
    run_as_root systemctl restart systemd-journald
    ok "journald limited to $max_size, $max_files files"
  else
    skip "journald already configured"
  fi
}

# -----------------------------------------------------------------------------
_configure_dnf_makecache_timer() {
  step "Reducing dnf-makecache frequency (weekly instead of hourly)"

  local override_dir="/etc/systemd/system/dnf-makecache.timer.d"
  local override_file="${override_dir}/override.conf"

  run_as_root mkdir -p "$override_dir"

  if [[ ! -f "$override_file" ]]; then
    run_as_root tee "$override_file" > /dev/null << 'TIMEREOF'
[Timer]
OnCalendar=
OnCalendar=weekly
RandomizedDelaySec=1h
TIMEREOF
    run_as_root systemctl daemon-reload
    ok "dnf-makecache scheduled weekly"
  else
    skip "dnf-makecache override already exists"
  fi
}

# Standalone entry point
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
  source "${SCRIPT_DIR}/utils.sh"
  source "${SCRIPT_DIR}/finitra-default.config"
  [[ -f "${HOME}/.config/finitra/finitra.config" ]] && \
    source "${HOME}/.config/finitra/finitra.config"
  module_40_optimizations
fi
