name: Validate Branch Name

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-name:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Branch Prefix
        run: |
          SOURCE_BRANCH="${{ github.event.pull_request.head.ref }}"
          echo "Validating branch: $SOURCE_BRANCH"
          
          # Regular expression with allowed prefixes
          PATTERN="^(feature|feat|bugfix|fix|hotfix|major|release|docs|chore)/.+$"
          
          if [[ ! "$SOURCE_BRANCH" =~ $PATTERN ]]; then
            echo "::error::Invalid branch name! The branch '$SOURCE_BRANCH' must start with one of the following prefixes followed by a slash (/): feature/, feat/, bugfix/, fix/, hotfix/, major/, release/, docs/, chore/"
            exit 1
          fi
          echo "Valid branch name!"
